#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
easy_admin:
  site_name: "squidmin"
  entities:
    Passwd:
      label: 'Users'
      class: App\Entity\Passwd
      list:
        fields:
          - id
          - 'user'
          - { property: 'user', type: 'text', label: 'UserName' }
          - password
          - { property: 'enabled', label: 'Account Status', type: 'toggle' }
          - fullname
          - comment
      form:
        fields:
          - 'user'
          - { property: 'user', type: 'text', label: 'UserName' }
          - 'password'
          - { property: 'password', type: 'text', label: 'Password' }
          - 'fullname'
          - { property: 'fullname', type: 'text', label: 'Full Name' }
          - 'comment'
          - { property: 'comment', type: 'text', label: 'Comment' }
          - 'enabled'
          - { property: 'enabled', type: 'choice', label: 'Account Status' , type_options: {choices: {'Enable':'1', 'Disable':'0'}}}
